### ISSUE TITLE
Investigate JIRA JSON API for loading data automatically into a JIRA instance

### ISSUE THREAD

**Issue by twsswt** [twsswt/bug_buddy_jira_plugin#11]
There's good documentation on the API in the reference manual.

**Comment by stephen-brown-socs** [comment]
note for self later: https://developer.atlassian.com/jiradev/jira-apis/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-create-issue

**Comment by twsswt** [comment]
Need to get a demonstrator of being able to populate a JIRA instance.

**Comment by stephen-brown-socs** [comment]
Currently creates tasks instead of bugs

**Comment by stephen-brown-socs** [comment]
This appears to be a terminology issue - JIRA Core only has tasks, not bugs
