### ISSUE TITLE
Acquire data to evaluate the effectiveness of the recommender

### ISSUE THREAD

**Issue by stephen-brown-socs** [twsswt/bug_buddy_jira_plugin#13]
http://openscience.us/repo/issues/bugreport.html looks like an interesting data set
It has assignee data for the first day of the report, along with later days (such as a week after, a month after). If the assignee has stabilised by day 30, can it be inferred that they resolved the issue?

Also the data set doesn't contain the text of the issues, just the metadata. Would need to program something to grab the actual text

**Comment by twsswt** [comment]
There's a firefox DB of issues - can you remember to include here?

**Comment by stephen-brown-socs** [comment]
http://openscience.us/repo/issues/bugreport.html is a dataset of firefox issues

**Comment by stephen-brown-socs** [comment]
This is a quick sketch of how I think the firefox evaluation dataset should interact with JIRA
![handcrafteduml](https://user-images.githubusercontent.com/32129555/31685228-2018214e-b37a-11e7-9f80-feea48e5a053.jpg)

**Comment by stephen-brown-socs** [comment]
This is effectively complete. The only things left to do for this are minor bugs and enhancements
