### ISSUE TITLE
Set up a review meeting with Obashi for about a months time.

### ISSUE THREAD

**Issue by twsswt** [twsswt/bug_buddy_jira_plugin#9]
@probablytom is supposed to be doing this for his PhD, so maybe liase with him too?

**Comment by probablytom** [comment]
@sbrown1992 FYI, that meeting looks like it'll *probably* happen Oct 25th, with the meeting for my PhD being around 10:00... maybe that's a good day to arrange this too?

**Comment by stephen-brown-socs** [comment]
@probablytom October 25th is the date of the placements conference. I'll need to be around the uni from 10 till 5 that day, but I'll be free for a few hours during it! Will find out when those are closer to the time

**Comment by stephen-brown-socs** [comment]
@twsswt Do you also want to attend this meeting? It might be incredibly hard to schedule around the placements conference if so, and may be worth moving to a different date

**Comment by stephen-brown-socs** [comment]
A meeting has been arranged for Friday 10th November
